# Use the official PostgreSQL image
FROM postgres
ARG SecretUser
ARG SecretPass

# Set environment variables for PostgreSQL
ENV SECRET_USER_VAR=$SecretUser
ENV SECRET_PASS_VAR=$SecretPass
ENV POSTGRES_USER=$SECRET_USER_VAR
ENV POSTGRES_PASSWORD=$SECRET_PASS_VAR
ENV POSTGRES_DB=inventory

# Expose the PostgreSQL port
EXPOSE 5432
