name: CICD

on: 
  workflow_dispatch: 
  
#  push:
#    branches: [main]

#  pull_request:
#    branches: [main]

jobs:
  unit-test: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v4
      - name: setup docker 
        uses: docker/setup-buildx-action@v3
      - name: Build and run Docker container
        run: |
         chmod +x $GITHUB_WORKSPACE/run_db.sh
         ./$GITHUB_WORKSPACE/run_db.sh
