name: CICD

on: 
  workflow_dispatch: 
  
#  push:
#    branches: [main]

#  pull_request:
#    branches: [main]

jobs:
  unit-test: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v4
      - name: setup docker 
        uses: docker/setup-buildx-action@v3
      - name: setup rust
        uses: actions-rs/toolchain@v1
        with: 
          toolchain: stable
      - run: cargo install diesel-cli  
      - name: Build and run Docker container
        run: |
         chmod +x run_db.sh
         ./run_db.sh
